# Generated by Django 4.1.5 on 2023-01-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='quantity_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
