# Generated by Django 4.1.5 on 2023-01-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produtos_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Products',
        ),
    ]
