# Generated by Django 4.1.5 on 2023-01-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sales_payment_alter_sales_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('non-existent product'), to='app.payments'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('non-existent product'), to='app.products'),
        ),
    ]
